[package]
name = "ogp-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
image = "0.25.5"
ratatui = "0.29.0"
reqwest = { version = "0.12.9", features = ["blocking"] }
scraper = "0.21.0"
